# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS-AFNetworking封装' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOS-AFNetworking封装
  pod 'AFNetworking', '3.1.0'
  pod 'YYCache'
  pod 'SDWebImage'
  pod 'YYModel'
  pod 'YYAsyncLayer'

end
